name: Linters

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install packages
        run: |
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Run Mypy
        run: mypy .

      - name: Run Ruff check
        run: ruff check --diff

      - name: Run Ruff format
        run: ruff format --diff

